name: SwiftFormat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swiftformat:
    name: Run SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat
        run: swiftformat .

      - name: Verify no formatting changes
        run: |
          if [[ -n "$(git diff --name-only)" ]]; then
            echo "Formatting issues detected. Please run 'swiftformat .' locally to fix.";
            exit 1;
          fi