name: SwiftPM Build & Test (All Apple Platforms)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        platform:
          - macOS
          - iOS
          - tvOS
          - watchOS
          - visionOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Swift and Xcode version
        run: |
          swift --version
          xcodebuild -version

      - name: Resolve Dependencies
        run: swift package resolve

      - name: Build for ${{ matrix.platform }}
        run: |
          case "${{ matrix.platform }}" in
            macOS)
              swift build
              ;;
            iOS)
              xcodebuild build -scheme EazyRestClient -destination 'generic/platform=iOS'
              ;;
            tvOS)
              xcodebuild build -scheme EazyRestClient -destination 'generic/platform=tvOS'
              ;;
            watchOS)
              xcodebuild build -scheme EazyRestClient -destination 'generic/platform=watchOS'
              ;;
            visionOS)
              xcodebuild build -scheme EazyRestClient -destination 'generic/platform=visionOS'
              ;;
          esac

      - name: Run SwiftPM Tests (macOS only)
        if: matrix.platform == 'macOS'
        run: swift test --enable-test-discovery
