name: SwiftPM Build & Test (All Apple Platforms)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        # We use a full, valid destination string in the matrix to ensure Xcode knows exactly what to do.
        # This is the key change to fix the errors.
        destination:
          - "platform=iOS Simulator,name=iPhone 15"
          - "platform=macOS"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)"
          - "platform=visionOS Simulator,name=Apple Vision Pro"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Swift and Xcode version
        run: |
          swift --version
          xcodebuild -version

      - name: Build and Test on ${{ matrix.destination }}
        run: |
          # 'xcodebuild test' handles both the build and test phases in a single command,
          # making the workflow more reliable and efficient.
          xcodebuild test -scheme EazyRestClient -destination "${{ matrix.destination }}" | xcbeautify
